spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-cndeepcoding-dev
---
spring:
  profiles: test
  application:
    name: springcloud-config-cndeepcoding-test